### ISSUE TITLE
ASIO Support

### ISSUE THREAD

**Issue by dhoomakethu** [bastibe/PySoundCard#34]
Hi ,

using apis() I could not see ASIO in the supported host api's , Is ASIO not supported by PySoundCard ? Is there a plan for the support ?

Regards
sanjay

**Comment by mgeier** [comment]
Just for reference:
There seem to be pre-compiled DLLs with ASIO support here: https://github.com/adfernandes/precompiled-portaudio-windows.
I didn't try them, though.

**Comment by bastibe** [comment]
If memory serves, these have debug printing turned on, which makes them pretty much unusable on the command line.

**Comment by mgeier** [comment]
I've created DLLs with ASIO support (and hopefully without this debugging-stuff): https://github.com/spatialaudio/portaudio-binaries
Those are used in https://github.com/spatialaudio/python-sounddevice, but they could of course also be used in PySoundCard.
