### ISSUE TITLE
adding __version__

### ISSUE THREAD

**Issue by peircej** [bastibe/PySoundCard#42]
At the moment I can't find a way to see what version of PySoundCard/File is installed. Could you add a `__version__` attribute?

**Comment by mgeier** [comment]
In another project I used something like this to avoid specifying the version number at two different places:

```Python
# this is inside of setup.py

# "import" __version__
for line in open("pysoundcard.py"):
    if line.startswith("__version__"):
        exec(line)
        break

setup(..., version=__version__, ...)
```

Would this be feasible for our case?

I know that `exec()` is generally dangerous, but would it be safe enough in this very case?

I found other solutions to this problem, often using regular expressions, but all of them adding large amounts of complicated code to `setup.py`.

**Comment by peircej** [comment]
For a first pass it's really simple to do with:
`from pysoundcard import __version__ `
in the setup.py

**Comment by mgeier** [comment]
This imports the module before the requirements are checked, i.e. if requirements are missing, they can never be installed.
In other words, this only works if PySoundCard is already installed (or at least all the dependencies).

Or am I missing something?

**Comment by mgeier** [comment]
Here's a link to the official documentation providing a few solutions to this problem:
https://packaging.python.org/en/latest/single_source_version.html

I think my solution is simpler than any of them and not less secure than the one using `exec()`/`execfile()`.

But I may be completely wrong ...

**Comment by peircej** [comment]
I see what you're saying, yes. In the package I develop the top layer of 
import (an __init__ file) does very little except for setting up 
__version__ and a couple of really core functions

But for pysoundcard, with all the functionality in the one file I can 
see this isn't ideal.

Or have a file called version that gets read by both setup.py and 
pysoundcard.py:
```python
with open('version') as f:
     __version__ = f.read().split()[0]
```

But this is overcomplicating things; it is a pretty limited use of 
exec() and I'm sure it won't hurt!

On 05/03/2015 16:00, Matthias Geier wrote:
>
> This imports the module before the requirements are checked, i.e. if 
> requirements are missing, they can never be installed.
> In other words, this only works if PySoundCard is already installed 
> (or at least all the dependencies).
>
> Or am I missing something?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/bastibe/PySoundCard/issues/42#issuecomment-77390464>.
>

-- 
Jonathan Peirce
Nottingham Visual Neuroscience

http://www.peirce.org.uk





This message and any attachment are intended solely for the addressee
and may contain confidential information. If you have received this
message in error, please send it back to me, and immediately delete it. 

Please do not use, copy or disclose the information contained in this
message or in any attachment.  Any views or opinions expressed by the
author of this email do not necessarily reflect the views of the
University of Nottingham.

This message has been checked for viruses but the contents of an
attachment may still contain software viruses which could damage your
computer system, you are advised to perform your own checks. Email
communications with the University of Nottingham may be monitored as
permitted by UK legislation.

**Comment by peircej** [comment]
Is there still no version info in the package? I'm trying to use pysoundcard as a dependency of a larger package but it makes it really hard given that the API is still changing and I can't detect which version a user has installed.

**Comment by bastibe** [comment]
Oh, I'm sorry. I forgot about this issue. I'll fix it tomorrow.

**Comment by bastibe** [comment]
OK, should be implemented now.

**Comment by peircej** [comment]
many thanks :-)
