### ISSUE TITLE
pysoundcard.devices deprecated/moved

### ISSUE THREAD

**Issue by stuaxo** [bastibe/PySoundCard#63]
Hi,
   In some old code I do ```from pysoundcard import devices``` this seems to not work on current pysoundcard, has it been moved or deprecated ?

S

**Comment by bastibe** [comment]
You can use `device_info()` to get a generator of all currently available devices, or `default_input_device()` and `default_output_device()` to get the current default devices.

**Comment by stuaxo** [comment]
Cheers, got my stuff working.

Also had to update to change from using Stream to InputStream, also parameters like input_channels > channels, buffer_width>buffersize etc.

**Comment by bastibe** [comment]
I'm sorry that I can't devote as much time to this project as it would need. But real life, and the horrors that lurk within portaudio, conspire against such a time investment.

**Comment by stuaxo** [comment]
Still good your able to respond - I notice that portaudio moved to git some time in the last year or two, so expect their speed to move somewhere above glacial which is good.
