### ISSUE TITLE
System audio recording?

### ISSUE THREAD

**Issue by slole** [bastibe/PySoundCard#66]
Can you record the audio that is being played to the speakers aka. "what you hear"? Is that on Linux and Windows? I am asking this because I'm developing: http://supercode.co.nf/ .

**Comment by bastibe** [comment]
As far as I know, you can not. Portaudio, the C library we rely on, does not support this. On Linux, you could use my newer library [SoundCard](https://github.com/bastibe/SoundCard), which on Linux uses pulseaudio, and exposes this feature: Use `all_microphones(exclude_monitors=False)`, and look for a sound card with the same name as your default speaker.

The audio libraries of the other operating systems do not support this feature, as far as I know.

**Comment by slole** [comment]
Thanks for the reply. I'll look into SoundCard. I was just curious because I was using Windows's WASAPI and up to this point and I was able to record system audio without a problem. If I won't be able to use SoundCard for my project I'll try to write my own wrappers for WASAPI and ALSA for QT.
